# Generated by Django 5.1.1 on 2024-09-29 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('top_logo', 'Top Logo'), ('highlight_category_section_one', 'Highlight, Category, Section Page-One'), ('highlight_category_section_two', 'Highlight, Category, Section Page-Two'), ('section_one', 'Frontpage Section One'), ('section_two', 'Frontpage Section Two'), ('section_three', 'Frontpage Section Three'), ('section_four', 'Frontpage Section Four'), ('section_five', 'Frontpage Section Five'), ('section_six', 'Frontpage Section Six'), ('category_one', 'Category One'), ('category_two', 'Category Two'), ('front_news_one', 'Front News One'), ('front_news_two', 'Front News Two'), ('front_news_three', 'Front News Three'), ('front_news_four', 'Front News Four'), ('section_category_details', 'Section Category Details page'), ('news_details', 'News Details'), ('news_details_side_ads_one', 'News Details Side One'), ('news_details_side_ads_two', 'News Details Side Two'), ('section_page_ads_one', 'Section page One'), ('section_page_ads_two', 'Section page Two')], max_length=50)),
                ('image', models.FileField(upload_to='ads/', verbose_name='Media')),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='', max_length=100, unique=True, verbose_name='Category Name (English)')),
                ('name_bn', models.CharField(default='', max_length=100, unique=True, verbose_name='বিভাগের বাংলা নাম')),
            ],
            options={
                'verbose_name': 'বিভাগ',
                'verbose_name_plural': 'বিভাগসমূহ',
            },
        ),
        migrations.CreateModel(
            name='Commenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('designation', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(default='img/logo.png', upload_to='commenters/', verbose_name='মন্তব্যকারীর ছবি (Commenter Image)')),
                ('social_media_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='epapers/')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Gallery Image')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short_caption', models.CharField(blank=True, max_length=200, verbose_name='Short Caption')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='', max_length=100, unique=True, verbose_name='Section Name (English)')),
                ('name_bn', models.CharField(default='', max_length=100, unique=True, verbose_name='সেকশনের বাংলা নাম')),
            ],
            options={
                'verbose_name': 'সেকশন',
                'verbose_name_plural': 'সেকশনসমূহ',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(verbose_name='YouTube URL')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('thumbnail_url', models.URLField(blank=True, null=True, verbose_name='Thumbnail URL')),
                ('highlighted', models.BooleanField(default=False, verbose_name='Highlighted')),
                ('highlight_until', models.DateTimeField(blank=True, null=True, verbose_name='Highlight Until')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryFrontPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category', unique=True, verbose_name='বিভাগ (Category)')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('today_comment', models.BooleanField(default=False)),
                ('serial_number', models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], null=True, verbose_name='Serial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয় (Active)')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.commenter')),
            ],
        ),
        migrations.CreateModel(
            name='NewsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='শিরোনাম ১ (Title 1)')),
                ('description', models.TextField(verbose_name='বর্ণনা ১ (Description 1)')),
                ('image', models.ImageField(blank=True, default='img/logo.png', null=True, upload_to='news_images/', verbose_name='ছবি ১ (Image 1)')),
                ('image_caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='ছবির ক্যাপশন ১ (Image Caption 1)')),
                ('link', models.URLField(blank=True, null=True, verbose_name='লিংক ১ (Link 1)')),
                ('link_caption1', models.CharField(blank=True, max_length=255, null=True, verbose_name='লিংক ক্যাপশন ১ (Link Caption 1)')),
                ('title2', models.CharField(blank=True, max_length=255, null=True, verbose_name='শিরোনাম ২ (Title 2)')),
                ('description2', models.TextField(blank=True, null=True, verbose_name='বর্ণনা ২ (Description 2)')),
                ('image2', models.ImageField(blank=True, default='img/logo.png', null=True, upload_to='news_images/', verbose_name='ছবি ২ (Image 2)')),
                ('image_caption2', models.CharField(blank=True, max_length=255, null=True, verbose_name='ছবির ক্যাপশন ২ (Image Caption 2)')),
                ('link2', models.URLField(blank=True, null=True, verbose_name='লিংক ২ (Link 2)')),
                ('link_caption2', models.CharField(blank=True, max_length=255, null=True, verbose_name='লিংক ক্যাপশন ২ (Link Caption 2)')),
                ('title3', models.CharField(blank=True, max_length=255, null=True, verbose_name='শিরোনাম ৩ (Title 3)')),
                ('description3', models.TextField(blank=True, null=True, verbose_name='বর্ণনা ৩ (Description 3)')),
                ('image3', models.ImageField(blank=True, default='img/logo.png', null=True, upload_to='news_images/', verbose_name='ছবি ৩ (Image 3)')),
                ('image_caption3', models.CharField(blank=True, max_length=255, null=True, verbose_name='ছবির ক্যাপশন ৩ (Image Caption 3)')),
                ('link3', models.URLField(blank=True, null=True, verbose_name='লিংক ৩ (Link 3)')),
                ('link_caption3', models.CharField(blank=True, max_length=255, null=True, verbose_name='লিংক ক্যাপশন ৩ (Link Caption 3)')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False, verbose_name='যাচাইকৃত (Verified)')),
                ('highlighted', models.BooleanField(default=False, verbose_name='বিশেষ খবর (Highlighted)')),
                ('breaking_news', models.BooleanField(default=False, verbose_name='ব্রেকিং নিউজ (Breaking News)')),
                ('section_highlighted', models.BooleanField(default=False, verbose_name='Section Highlighted')),
                ('for_you', models.BooleanField(default=False, verbose_name='আপনার জন্য (For You)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='তৈরি হওয়ার তারিখ (Created At)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='বিভাগ (Category)')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.section', verbose_name='সেকশন (Section)')),
            ],
            options={
                'verbose_name': 'সংবাদ তালিকা (News List)',
                'verbose_name_plural': 'সংবাদ তালিকাসমূহ (News Lists)',
            },
        ),
        migrations.CreateModel(
            name='FrontPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], unique=True, verbose_name='সিরিয়াল (Serial)')),
                ('front_page_until', models.DateTimeField(blank=True, null=True, verbose_name='ফ্রন্ট পেজ পর্যন্ত সময় (Front Page Until)')),
                ('news_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='front_page', to='home.newslist', verbose_name='সংবাদ (News)')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='home.section'),
        ),
    ]
