# Generated by Django 5.1.1 on 2024-09-29 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_category_section_section_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='home.category'),
        ),
    ]
