# Generated by Django 5.1.1 on 2024-09-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_section_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='Category',
        ),
        migrations.AddField(
            model_name='section',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='home.category'),
        ),
    ]
