# Generated by Django 5.1.1 on 2024-09-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_section_category_section_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='category',
        ),
        migrations.AddField(
            model_name='section',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='sections', to='home.category'),
        ),
    ]
