# Generated by Django 5.1.1 on 2024-09-29 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_section_category_section_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.section', verbose_name='সেকশন (Section)'),
        ),
    ]
