# Generated by Django 5.1.1 on 2024-09-29 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_newslist_category_alter_newslist_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category', unique=True, verbose_name='বিভাগ (Category)'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.section', unique=True, verbose_name='সেকশন (Section)'),
        ),
    ]
