# Generated by Django 5.1.1 on 2024-09-30 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_newslist_category_alter_newslist_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category', verbose_name='বিভাগ (Category)'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.section', verbose_name='সেকশন (Section)'),
        ),
    ]
