# Generated by Django 5.1.1 on 2024-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_newslist_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_frontend',
            field=models.BooleanField(default=True, verbose_name='Show in Frontend'),
        ),
    ]
