# Generated by Django 5.1.1 on 2024-09-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_category_show_in_frontend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='show_in_frontend',
            new_name='show_in_frontpage',
        ),
    ]
