# Generated by Django 5.1.1 on 2024-09-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_show_in_frontend_category_show_in_frontpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='show_in_frontpage',
            field=models.BooleanField(default=True, verbose_name='Show in Front Page'),
        ),
    ]
