# Generated by Django 5.1.1 on 2024-09-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_newslist_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='home.section', verbose_name='সেকশন (Section)'),
        ),
    ]
