# Generated by Django 5.1.1 on 2024-09-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_newslist_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description_en', models.TextField(verbose_name='Description in English')),
                ('description_bn', models.TextField(verbose_name='Description in Bangla')),
                ('media', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Media (Image or PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
