# Generated by Django 5.1.1 on 2024-09-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_advertisementchart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementchart',
            name='description_bn',
        ),
        migrations.RemoveField(
            model_name='advertisementchart',
            name='description_en',
        ),
        migrations.AddField(
            model_name='advertisementchart',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='advertisementchart',
            name='title',
            field=models.TextField(max_length=255, verbose_name='শিরোনাম ১ (Title 1)'),
        ),
    ]
