# Generated by Django 5.1.1 on 2024-09-30 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_advertisementchart_description_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category', verbose_name='বিভাগ (Category)'),
        ),
        migrations.AlterField(
            model_name='advertisementchart',
            name='title',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='শিরোনাম ১ (Title 1)'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='title',
            field=models.TextField(max_length=255, verbose_name='শিরোনাম ১ (Title 1)'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='title2',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='শিরোনাম ২ (Title 2)'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='title3',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='শিরোনাম ৩ (Title 3)'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category', verbose_name='বিভাগ (Category)'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='title',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.TextField(max_length=255, verbose_name='Title'),
        ),
    ]
