# Generated by Django 5.1.1 on 2024-09-30 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_video_category_alter_advertisementchart_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogallery',
            name='short_caption',
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='title',
        ),
        migrations.AddField(
            model_name='photogallery',
            name='caption',
            field=models.TextField(blank=True, verbose_name='ক্যাপশন'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='বিকল্প টেক্সট (Alt Text)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('top_logo', 'Top Logo'), ('highlight_category_section_one', 'Highlight, Category, Section Page-One'), ('highlight_category_section_two', 'Highlight, Category, Section Page-Two'), ('section_one', 'Frontpage Section One'), ('section_two', 'Frontpage Section Two'), ('section_three', 'Frontpage Section Three'), ('section_four', 'Frontpage Section Four'), ('section_five', 'Frontpage Section Five'), ('section_six', 'Frontpage Section Six'), ('category_one', 'Category One'), ('category_two', 'Category Two'), ('front_news_one', 'Front News One'), ('front_news_two', 'Front News Two'), ('front_news_three', 'Front News Three'), ('front_news_four', 'Front News Four'), ('section_category_details', 'Section Category Details page'), ('news_details', 'News Details'), ('news_details_side_ads_one', 'News Details Side One'), ('news_details_side_ads_two', 'News Details Side Two'), ('section_page_ads_one', 'Section page One'), ('section_page_ads_two', 'Section page Two')], max_length=50, verbose_name='ক্যাটেগরি (Category)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='end_date',
            field=models.DateTimeField(verbose_name='শেষ করার তারিখ (End Date)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.FileField(upload_to='ads/', verbose_name='মিডিয়া (Media)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='সক্রিয় (Active)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='লিংক (Link)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='start_date',
            field=models.DateTimeField(verbose_name='শুরু করার তারিখ (Start Date)'),
        ),
        migrations.AlterField(
            model_name='advertisementchart',
            name='title',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='শিরোনাম (Title)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_bn',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='বিভাগের বাংলা নাম (Category Name in Bangla)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='বিভাগের নাম (Category Name in English)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_in_frontpage',
            field=models.BooleanField(default=True, verbose_name='ফ্রন্ট পেজে দেখান (Show in Front Page)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হওয়ার তারিখ (Created At)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], null=True, verbose_name='ক্রমানুযায়ী (Serial)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='today_comment',
            field=models.BooleanField(default=False, verbose_name='আজকের মন্তব্য (Today Comment)'),
        ),
        migrations.AlterField(
            model_name='epaper',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='সক্রিয় (Active)'),
        ),
        migrations.AlterField(
            model_name='epaper',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='যাচাইকৃত (Verified)'),
        ),
        migrations.AlterField(
            model_name='epaper',
            name='pdf',
            field=models.FileField(upload_to='epapers/', verbose_name='পিডিএফ ফাইল (PDF File)'),
        ),
        migrations.AlterField(
            model_name='epaper',
            name='title',
            field=models.CharField(max_length=255, verbose_name='শিরোনাম (Title)'),
        ),
        migrations.AlterField(
            model_name='epaper',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='আপলোডের সময় (Upload Time)'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='title',
            field=models.TextField(verbose_name='শিরোনাম ১ (Title 1)'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='title2',
            field=models.TextField(blank=True, null=True, verbose_name='শিরোনাম ২ (Title 2)'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='title3',
            field=models.TextField(blank=True, null=True, verbose_name='শিরোনাম ৩ (Title 3)'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='ছবি'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='যাচাইক্ত'),
        ),
        migrations.AlterField(
            model_name='section',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='sections', to='home.category', verbose_name='বিভাগসমূহ (Categories)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name_bn',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='সেকশনের বাংলা নাম (Section Name in Bangla)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name_en',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='সেকশনের নাম (Section Name in English)'),
        ),
    ]
