# Generated by Django 5.1.1 on 2024-09-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_photogallery_short_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementchart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হওয়ার তারিখ (Created At)'),
        ),
        migrations.AlterField(
            model_name='advertisementchart',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='সক্রিয় (Active)'),
        ),
        migrations.AlterField(
            model_name='advertisementchart',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='ফাইল আপ্লোড করুন (Upload File)'),
        ),
    ]
