# Generated by Django 5.1.1 on 2024-10-04 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_advertisementchart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfrontpagemodel',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='বিভাগ (Category)'),
        ),
    ]
