# Generated by Django 5.1.1 on 2024-10-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_categoryfrontpagemodel_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryFrontPageModel',
        ),
    ]
