# Generated by Django 5.1.1 on 2024-10-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_delete_categoryfrontpagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslist',
            name='red_tag',
            field=models.TextField(default='', verbose_name='লাল শিরোনাম (Red Tag)'),
        ),
    ]
