# Generated by Django 5.1.1 on 2024-10-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_newslist_red_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='red_tag',
            field=models.TextField(blank=True, default='', null=True, verbose_name='লাল শিরোনাম (Red Tag)'),
        ),
    ]
