# Generated by Django 5.1.1 on 2024-10-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_newslist_red_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='popup_ads/')),
                ('link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
