# Generated by Django 5.1.1 on 2024-10-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_popupad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popupad',
            name='is_active',
        ),
    ]
