# Generated by Django 5.1.1 on 2024-10-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_popupad_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupad',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
