# Generated by Django 5.1.2 on 2024-10-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_popupad_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='newslist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
        migrations.AddField(
            model_name='newslist',
            name='highlighted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='হাইলাইট করা তারিখ (Highlighted At)'),
        ),
    ]
