# Generated by Django 5.1.2 on 2024-10-26 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_category_options_alter_newslist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNavbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.section')),
            ],
            options={
                'verbose_name': 'Mobile Navbar',
                'verbose_name_plural': 'Mobile Navbars',
                'constraints': [models.CheckConstraint(condition=models.Q(('section__isnull', False), ('category__isnull', False), _connector='OR'), name='section_or_category_required_mobile')],
            },
        ),
        migrations.CreateModel(
            name='PCNavbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, editable=False, max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.section')),
            ],
            options={
                'verbose_name': 'PC Navbar',
                'verbose_name_plural': 'PC Navbars',
                'constraints': [models.CheckConstraint(condition=models.Q(('section__isnull', False), ('category__isnull', False), _connector='OR'), name='section_or_category_required')],
            },
        ),
    ]
