# Generated by Django 5.1.2 on 2024-10-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_mobilenavbar_pcnavbar'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mobilenavbar',
            name='section_or_category_required_mobile',
        ),
        migrations.RemoveConstraint(
            model_name='pcnavbar',
            name='section_or_category_required',
        ),
        migrations.AddConstraint(
            model_name='mobilenavbar',
            constraint=models.CheckConstraint(condition=models.Q(('section__isnull', False), ('category__isnull', False), _connector='OR'), name='mobilenav_section_or_category_required'),
        ),
        migrations.AddConstraint(
            model_name='pcnavbar',
            constraint=models.CheckConstraint(condition=models.Q(('section__isnull', False), ('category__isnull', False), _connector='OR'), name='pcnav_section_or_category_required'),
        ),
    ]
