# Generated by Django 5.1.2 on 2024-10-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_mobilenavbar_section_or_category_required_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslist',
            name='serial_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
