# Generated by Django 5.1.2 on 2024-10-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_newslist_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslist',
            name='highlighted_at',
        ),
        migrations.RemoveField(
            model_name='newslist',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='newslist',
            name='highlighted_serial',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Highlighted Serial'),
        ),
    ]
