# Generated by Django 5.1.2 on 2024-10-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_remove_newslist_highlighted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslist',
            name='highlighted_serial',
        ),
        migrations.AddField(
            model_name='newslist',
            name='highlighted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='হাইলাইট করা তারিখ (Highlighted At)'),
        ),
    ]
