# Generated by Django 5.1.2 on 2024-10-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_newslist_highlighted_serial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcnavbar',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pcnavbar',
            name='section',
        ),
        migrations.DeleteModel(
            name='MobileNavbar',
        ),
        migrations.DeleteModel(
            name='PCNavbar',
        ),
    ]
