# Generated by Django 5.1.2 on 2024-10-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_pcnavbar_category_remove_pcnavbar_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.TextField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
