# Generated by Django 5.1.2 on 2024-11-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogallery',
            name='category',
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('top_logo', 'Top Logo'), ('front_news_one', 'Homepage Highlighted Ads One'), ('front_news_two', 'Homepage Highlighted Ads Two'), ('front_news_three', 'Selected News Ads One'), ('front_news_four', 'Selected News Ads Four'), ('section_one', 'Frontpage Section One'), ('section_two', 'Frontpage Section Two'), ('section_three', 'Frontpage Section Three'), ('section_four', 'Frontpage Section Four'), ('section_five', 'Frontpage Section Five'), ('section_six', 'Frontpage Section Six'), ('highlight_category_section_one', 'Between Frontpage Category Ads One'), ('highlight_category_section_two', 'Between Frontpage Category Ads Two'), ('news_details', 'News Details'), ('news_details_side_ads_one', 'News Details Side Ads One'), ('news_details_side_ads_two', 'News Details Side Ads Two'), ('section_category_ad', 'Section & Category Pages'), ('section_page_ads_one', 'Section page Side Ads One'), ('section_page_ads_two', 'Section page Side Ads Two')], max_length=50, verbose_name='ক্যাটেগরি (Category)'),
        ),
    ]
