# Generated by Django 5.1.2 on 2024-11-24 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_photogallery_category_alter_ad_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='today_comment',
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('top_logo', 'Top Logo'), ('front_news_one', 'Homepage Highlighted Ads One'), ('front_news_two', 'Homepage Highlighted Ads Two'), ('front_news_three', 'Selected News Ads One'), ('front_news_four', 'Selected News Ads Two'), ('section_one', 'Frontpage Section One'), ('section_two', 'Frontpage Section Two'), ('section_three', 'Frontpage Section Three'), ('section_four', 'Frontpage Section Four'), ('section_five', 'Frontpage Section Five'), ('section_six', 'Frontpage Section Six'), ('highlight_category_section_one', 'Between Frontpage Category Ads One'), ('highlight_category_section_two', 'Between Frontpage Category Ads Two'), ('news_details', 'News Details'), ('news_details_side_ads_one', 'News Details Side Ads One'), ('news_details_side_ads_two', 'News Details Side Ads Two'), ('section_category_ad', 'Section & Category Pages'), ('section_page_ads_one', 'Section page Side Ads One'), ('section_page_ads_two', 'Section page Side Ads Two')], max_length=50, verbose_name='ক্যাটেগরি (Category)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.commenter', verbose_name='মন্তব্যকারী (Commenter)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(verbose_name='বিবরণ (Description)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=100, verbose_name='শিরোনাম (Title)'),
        ),
        migrations.AlterField(
            model_name='commenter',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='উপাধি (Designation)'),
        ),
        migrations.AlterField(
            model_name='commenter',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='নাম (Name)'),
        ),
        migrations.AlterField(
            model_name='commenter',
            name='social_media_link',
            field=models.URLField(blank=True, null=True, verbose_name='সোশ্যাল মিডিয়া লিঙ্ক (Social Media Link)'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='যাচাইকৃত '),
        ),
    ]
