# Generated by Django 5.1.2 on 2024-11-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_remove_comment_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontpage',
            name='front_page_until',
        ),
    ]
