# Generated by Django 5.1.2 on 2024-11-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_remove_frontpage_front_page_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
    ]
