# Generated by Django 5.1.2 on 2024-11-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_remove_video_description_remove_video_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epaper',
            name='is_verified',
        ),
    ]
