# Generated by Django 5.1.2 on 2024-11-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_epaper_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='যাচাইকৃত '),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='সক্রিয় (Active)'),
        ),
        migrations.AlterField(
            model_name='advertisementchart',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='সক্রিয় (Active)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='সক্রিয় (Active)'),
        ),
        migrations.AlterField(
            model_name='epaper',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='সক্রিয় (Active)'),
        ),
        migrations.AlterField(
            model_name='popupad',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
