# Generated by Django 5.1.2 on 2024-11-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_video_verified_alter_ad_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementChartBangla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=255, null=True, verbose_name='শিরোনাম (Title)')),
                ('media', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='ফাইল আপ্লোড করুন (Upload File)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হওয়ার তারিখ (Created At)')),
                ('is_active', models.BooleanField(default=False, verbose_name='সক্রিয় (Active)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
