# Generated by Django 5.1.2 on 2024-11-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_advertisementchartbangla'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvertisementChartBangla',
            new_name='AdvertisementBanglaChart',
        ),
    ]
