# Generated by Django 5.1.2 on 2024-11-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_rename_advertisementchartbangla_advertisementbanglachart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupad',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
