# Generated by Django 5.1.2 on 2024-11-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_popupad_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvertisementChart',
            new_name='AdvertisementOfflineChart',
        ),
        migrations.RenameModel(
            old_name='AdvertisementBanglaChart',
            new_name='AdvertisementOnlineChart',
        ),
    ]
