# Generated by Django 5.1.2 on 2024-11-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_rename_advertisementchart_advertisementofflinechart_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
