# Generated by Django 5.1.2 on 2024-11-26 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(verbose_name='YouTube URL')),
                ('title', models.TextField(blank=True, max_length=255, verbose_name='Title')),
                ('reporter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reporter')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('news_link', models.URLField(blank=True, null=True, verbose_name='Related News Link')),
                ('highlighted', models.BooleanField(default=False, verbose_name='Highlighted')),
                ('highlighted_at', models.DateTimeField(blank=True, null=True, verbose_name='Highlighted At')),
                ('highlight_until', models.DateTimeField(blank=True, null=True, verbose_name='Highlight Until')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('section_highlighted', models.BooleanField(default=False, verbose_name='Section Highlighted')),
                ('breaking_news', models.BooleanField(default=False, verbose_name='Breaking News')),
                ('for_you', models.BooleanField(default=False, verbose_name='For You')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category', verbose_name='বিভাগ (Category)')),
            ],
        ),
    ]
