# Generated by Django 5.1.2 on 2024-11-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='breaking_news',
        ),
        migrations.RemoveField(
            model_name='video',
            name='for_you',
        ),
    ]
