# Generated by Django 5.1.2 on 2024-11-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_remove_video_breaking_news_remove_video_for_you'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='section_highlighted',
        ),
    ]
