# Generated by Django 5.1.2 on 2024-11-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_remove_video_section_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Video Code'),
        ),
    ]
