# Generated by Django 5.1.2 on 2024-11-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_video_video_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_code',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True, verbose_name='Video Code'),
        ),
    ]
