# Generated by Django 5.1.2 on 2024-11-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_video_video_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Video Code'),
        ),
    ]
