# Generated by Django 5.1.2 on 2024-11-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_alter_video_video_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='highlighted_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_code',
        ),
    ]
