# Generated by Django 5.1.2 on 2024-11-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_remove_video_highlighted_at_remove_video_video_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Video Code'),
        ),
    ]
