# Generated by Django 5.1.2 on 2024-11-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_video_video_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='highlighted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Highlighted At'),
        ),
    ]
