# Generated by Django 5.1.2 on 2024-11-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_video_highlighted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslist',
            name='reporter',
            field=models.TextField(blank=True, default='', null=True, verbose_name='প্রতিবেদক (Reporter)'),
        ),
    ]
