# Generated by Django 5.1.2 on 2024-11-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_newslist_reporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
    ]
