# Generated by Django 5.1.2 on 2024-11-28 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category', verbose_name='বিভাগ (Category)'),
        ),
    ]
