# Generated by Django 5.1.2 on 2024-11-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_photogallery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='news_link',
            field=models.URLField(blank=True, null=True, verbose_name='Related News Link'),
        ),
    ]
