# Generated by Django 5.1.2 on 2024-12-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_photogallery_news_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name_1', models.CharField(blank=True, help_text='প্রথম ফিল্ডের নাম', max_length=100, null=True)),
                ('field_value_1', models.CharField(blank=True, help_text='প্রথম ফিল্ডের মান', max_length=255, null=True)),
                ('field_name_2', models.CharField(blank=True, help_text='দ্বিতীয় ফিল্ডের নাম (ঐচ্ছিক)', max_length=100, null=True)),
                ('field_value_2', models.CharField(blank=True, help_text='দ্বিতীয় ফিল্ডের মান (ঐচ্ছিক)', max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, help_text='মোবাইল নম্বর', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, help_text='ইমেইল', max_length=254, null=True)),
                ('ads_email', models.EmailField(blank=True, help_text='বিজ্ঞাপনের ইমেইল', max_length=254, null=True)),
                ('footer_description', models.TextField(blank=True, help_text='ফুটার বর্ণনা', null=True)),
            ],
        ),
    ]
