# Generated by Django 5.1.2 on 2024-12-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='field_name_3',
            field=models.CharField(blank=True, help_text='তৃতীয় ফিল্ডের নাম (ঐচ্ছিক)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='field_value_3',
            field=models.CharField(blank=True, help_text='তৃতীয় ফিল্ডের মান (ঐচ্ছিক)', max_length=255, null=True),
        ),
    ]
