# Generated by Django 5.1.2 on 2024-12-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_footer_field_name_3_footer_field_value_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='field_name_3',
        ),
        migrations.AlterField(
            model_name='footer',
            name='field_value_3',
            field=models.CharField(blank=True, help_text='তৃতীয় ফিল্ডের মান (ঐচ্ছিক)', max_length=1000, null=True),
        ),
    ]
