# Generated by Django 5.1.2 on 2024-12-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_remove_footer_field_name_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='field_value_3',
            field=models.TextField(blank=True, help_text='তৃতীয় ফিল্ডের মান (ঐচ্ছিক)', max_length=1000, null=True),
        ),
    ]
