# Generated by Django 5.1.2 on 2024-12-24 15:54

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_alter_footer_field_value_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='field_value_3',
            field=models.TextField(blank=True, help_text='তৃতীয় ফিল্ডের মান (ঐচ্ছিক)', null=True, validators=[home.models.validate_excluding_spaces]),
        ),
    ]
