# Generated by Django 5.1.2 on 2024-12-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_alter_footer_field_value_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100, verbose_name='Title (English)')),
                ('address_en', models.TextField(verbose_name='Address (English)')),
                ('phone_en', models.CharField(max_length=50, verbose_name='Phone (English)')),
                ('mobile_en', models.CharField(max_length=50, verbose_name='Mobile (English)')),
                ('email_news_en', models.EmailField(max_length=254, verbose_name='News Email (English)')),
                ('email_ads_en', models.EmailField(max_length=254, verbose_name='Ads Email (English)')),
                ('fax_en', models.CharField(max_length=50, verbose_name='Fax (English)')),
                ('title_bn', models.CharField(max_length=100, verbose_name='Title (Bengali)')),
                ('address_bn', models.TextField(verbose_name='Address (Bengali)')),
                ('phone_bn', models.CharField(max_length=50, verbose_name='Phone (Bengali)')),
                ('mobile_bn', models.CharField(max_length=50, verbose_name='Mobile (Bengali)')),
                ('email_news_bn', models.EmailField(max_length=254, verbose_name='News Email (Bengali)')),
                ('email_ads_bn', models.EmailField(max_length=254, verbose_name='Ads Email (Bengali)')),
                ('fax_bn', models.CharField(max_length=50, verbose_name='Fax (Bengali)')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
