# Generated by Django 5.1.2 on 2024-12-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_contactinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='address_bn',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='fax_bn',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='fax_en',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_bn1_title',
            field=models.TextField(default='', max_length=800, verbose_name='Address-1-Title (Bengali)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_bn1_value',
            field=models.TextField(default='', max_length=800, verbose_name='Address-1 (Bengali)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_bn2_title',
            field=models.TextField(default='', max_length=800, verbose_name='Address-2-Title (Bengali)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_bn2_value',
            field=models.TextField(default='', max_length=800, verbose_name='Address-2 (Bengali)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_en1_title',
            field=models.TextField(default='', max_length=500, verbose_name='Address-1-Title (English)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_en1_value',
            field=models.TextField(default='', max_length=500, verbose_name='Address-1 (English)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_en2_title',
            field=models.TextField(default='', max_length=500, verbose_name='Address-2-Title (English)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_en2_value',
            field=models.TextField(default='', max_length=500, verbose_name='Address-2 (English)'),
        ),
    ]
