# Generated by Django 5.1.2 on 2025-01-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_remove_contactinfo_address_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='mobile_bn_2',
            field=models.CharField(default='', max_length=50, verbose_name='Mobile Number 2 (Bengali)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='mobile_en2',
            field=models.CharField(default='', max_length=50, verbose_name='Mobile Number 2 (English)'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='mobile_bn',
            field=models.CharField(default='', max_length=50, verbose_name='Mobile (Bengali)'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='mobile_en',
            field=models.CharField(default='', max_length=50, verbose_name='Mobile (English)'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_bn',
            field=models.CharField(default='', max_length=50, verbose_name='Phone (Bengali)'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_en',
            field=models.CharField(default='', max_length=50, verbose_name='Phone (English)'),
        ),
    ]
