# Generated by Django 5.1.2 on 2025-01-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_contactinfo_mobile_bn_2_contactinfo_mobile_en2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='mobile_bn',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Mobile (Bengali)'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='mobile_bn_2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Mobile Number 2 (Bengali)'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='mobile_en',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Mobile (English)'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='mobile_en2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Mobile Number 2 (English)'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_bn',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Phone (Bengali)'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_en',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Phone (English)'),
        ),
    ]
