# Generated by Django 5.1.2 on 2025-01-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_alter_contactinfo_mobile_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='publication_name',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Publication Name (English)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='publication_name_bn',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Publication Name (English)'),
        ),
    ]
