# Generated by Django 5.1.2 on 2025-01-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_contactinfo_publication_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='publication_name_bn',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Publication Name (Bengali)'),
        ),
    ]
