# Generated by Django 5.1.2 on 2025-01-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_alter_contactinfo_publication_name_bn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='mobile_bn_2',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='mobile_en2',
        ),
    ]
