# Generated by Django 5.1.2 on 2025-01-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_remove_contactinfo_mobile_bn_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='email_ads_bn',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='email_news_bn',
        ),
        migrations.AddField(
            model_name='footer',
            name='telephone',
            field=models.CharField(blank=True, help_text='টেলিফোন নম্বর', max_length=15, null=True),
        ),
    ]
