# Generated by Django 5.1.2 on 2025-02-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_alter_epaper_options_remove_footer_telephone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epaper',
            options={},
        ),
        migrations.RemoveField(
            model_name='epaper',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='epaper',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='epaper',
            name='pdf_file',
            field=models.FileField(default='', upload_to='epapers/'),
        ),
        migrations.AlterField(
            model_name='epaper',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
