# Generated by Django 5.1.2 on 2025-02-15 01:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_alter_epaper_options_remove_epaper_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epaper',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
