# Generated by Django 5.1.2 on 2025-02-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_epaper_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epaper',
            name='upload_time',
            field=models.DateTimeField(),
        ),
    ]
